/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCashflowRouteImport } from './routes/_authenticated/cashflow'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedScheduleIndexRouteImport } from './routes/_authenticated/schedule.index'
import { Route as AuthenticatedRoomIndexRouteImport } from './routes/_authenticated/room.index'
import { Route as AuthenticatedScheduleCategoryKeyRouteImport } from './routes/_authenticated/schedule.$categoryKey'
import { Route as AuthenticatedRoomRoomIdRouteImport } from './routes/_authenticated/room.$roomId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashflowRoute = AuthenticatedCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleIndexRoute =
  AuthenticatedScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomIndexRoute = AuthenticatedRoomIndexRouteImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleCategoryKeyRoute =
  AuthenticatedScheduleCategoryKeyRouteImport.update({
    id: '/schedule/$categoryKey',
    path: '/schedule/$categoryKey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomRoomIdRoute = AuthenticatedRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/cashflow': typeof AuthenticatedCashflowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
  '/schedule/$categoryKey': typeof AuthenticatedScheduleCategoryKeyRoute
  '/room/': typeof AuthenticatedRoomIndexRoute
  '/schedule/': typeof AuthenticatedScheduleIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/cashflow': typeof AuthenticatedCashflowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/': typeof AuthenticatedIndexRoute
  '/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
  '/schedule/$categoryKey': typeof AuthenticatedScheduleCategoryKeyRoute
  '/room': typeof AuthenticatedRoomIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/cashflow': typeof AuthenticatedCashflowRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
  '/_authenticated/schedule/$categoryKey': typeof AuthenticatedScheduleCategoryKeyRoute
  '/_authenticated/room/': typeof AuthenticatedRoomIndexRoute
  '/_authenticated/schedule/': typeof AuthenticatedScheduleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/approvals'
    | '/budget'
    | '/cashflow'
    | '/dashboard'
    | '/map'
    | '/room/$roomId'
    | '/schedule/$categoryKey'
    | '/room/'
    | '/schedule/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/approvals'
    | '/budget'
    | '/cashflow'
    | '/dashboard'
    | '/map'
    | '/'
    | '/room/$roomId'
    | '/schedule/$categoryKey'
    | '/room'
    | '/schedule'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/approvals'
    | '/_authenticated/budget'
    | '/_authenticated/cashflow'
    | '/_authenticated/dashboard'
    | '/_authenticated/map'
    | '/_authenticated/'
    | '/_authenticated/room/$roomId'
    | '/_authenticated/schedule/$categoryKey'
    | '/_authenticated/room/'
    | '/_authenticated/schedule/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashflow': {
      id: '/_authenticated/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AuthenticatedCashflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule/': {
      id: '/_authenticated/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AuthenticatedScheduleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room/': {
      id: '/_authenticated/room/'
      path: '/room'
      fullPath: '/room/'
      preLoaderRoute: typeof AuthenticatedRoomIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule/$categoryKey': {
      id: '/_authenticated/schedule/$categoryKey'
      path: '/schedule/$categoryKey'
      fullPath: '/schedule/$categoryKey'
      preLoaderRoute: typeof AuthenticatedScheduleCategoryKeyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room/$roomId': {
      id: '/_authenticated/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedCashflowRoute: typeof AuthenticatedCashflowRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRoomRoomIdRoute: typeof AuthenticatedRoomRoomIdRoute
  AuthenticatedScheduleCategoryKeyRoute: typeof AuthenticatedScheduleCategoryKeyRoute
  AuthenticatedRoomIndexRoute: typeof AuthenticatedRoomIndexRoute
  AuthenticatedScheduleIndexRoute: typeof AuthenticatedScheduleIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedCashflowRoute: AuthenticatedCashflowRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRoomRoomIdRoute: AuthenticatedRoomRoomIdRoute,
  AuthenticatedScheduleCategoryKeyRoute: AuthenticatedScheduleCategoryKeyRoute,
  AuthenticatedRoomIndexRoute: AuthenticatedRoomIndexRoute,
  AuthenticatedScheduleIndexRoute: AuthenticatedScheduleIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
